Repository googleapis/java-memcache, pull requests merged in 2020-09, with the labels that each got.

#143 chore: regenerate README
  README.md
  synth.metadata
Labels: api: memcache, cla: yes, context: none

#145 chore: regenerate templates
  .github/CODEOWNERS
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#159 chore: regenerate README
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#161 chore: add repo settings configuration
  .github/sync-repo-settings.yaml
Labels: api: memcache, automerge, cla: yes

#162 build(java): use yoshi-approver token for auto-approve
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: memcache, automerge, cla: yes, context: full

#168 chore: regenerate templates
  .github/readme/synth.py
  .github/workflows/auto-release.yaml
  .kokoro/continuous/readme.cfg
  .kokoro/readme.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#170 build: rename samples lint workflow to checkstyle to disambiguate branch protection with unit lint
  .github/workflows/samples.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full
