Repository googleapis/java-memcache, pull requests merged in 2020-06, with the labels that each got.

#78 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#71 build: Support for cloud-rad & v2
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  google-cloud-memcache-bom/pom.xml
Labels: cla: yes

#79 chore: regenerate with updated protoc
  proto-google-cloud-memcache-v1beta2/src/main/java/com/google/cloud/memcache/v1beta2/ApplyParametersRequest.java
  proto-google-cloud-memcache-v1beta2/src/main/java/com/google/cloud/memcache/v1beta2/CreateInstanceRequest.java
  proto-google-cloud-memcache-v1beta2/src/main/java/com/google/cloud/memcache/v1beta2/DeleteInstanceRequest.java
  proto-google-cloud-memcache-v1beta2/src/main/java/com/google/cloud/memcache/v1beta2/GetInstanceRequest.java
  proto-google-cloud-memcache-v1beta2/src/main/java/com/google/cloud/memcache/v1beta2/Instance.java
  proto-google-cloud-memcache-v1beta2/src/main/java/com/google/cloud/memcache/v1beta2/ListInstancesRequest.java
  proto-google-cloud-memcache-v1beta2/src/main/java/com/google/cloud/memcache/v1beta2/ListInstancesResponse.java
  proto-google-cloud-memcache-v1beta2/src/main/java/com/google/cloud/memcache/v1beta2/LocationMetadata.java
  proto-google-cloud-memcache-v1beta2/src/main/java/com/google/cloud/memcache/v1beta2/MemcacheParameters.java
  proto-google-cloud-memcache-v1beta2/src/main/java/com/google/cloud/memcache/v1beta2/MemcacheVersion.java
  proto-google-cloud-memcache-v1beta2/src/main/java/com/google/cloud/memcache/v1beta2/OperationMetadata.java
  proto-google-cloud-memcache-v1beta2/src/main/java/com/google/cloud/memcache/v1beta2/UpdateInstanceRequest.java
  proto-google-cloud-memcache-v1beta2/src/main/java/com/google/cloud/memcache/v1beta2/UpdateParametersRequest.java
  synth.metadata
Labels: automerge, cla: yes, context: full

#84 chore(java_templates): add default CODEOWNERS files for samples reviews
  .github/CODEOWNERS
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: automerge, cla: yes, context: partial

#86 chore: turn on renovate-bot master issue for java repos
  renovate.json
  synth.metadata
Labels: automerge, cla: yes, context: full

#89 build(java): skip lint on samples directory
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#94 docs: Change relative URLs to absolute URLs to fix broken links.
  README.md
  proto-google-cloud-memcache-v1beta2/src/main/java/com/google/cloud/memcache/v1beta2/Instance.java
  proto-google-cloud-memcache-v1beta2/src/main/java/com/google/cloud/memcache/v1beta2/InstanceOrBuilder.java
  proto-google-cloud-memcache-v1beta2/src/main/proto/google/cloud/memcache/v1beta2/cloud_memcache.proto
  synth.metadata
Labels: automerge, cla: yes, context: partial

#99 ci: switch to secret manager for sample/integration tests
  .kokoro/build.sh
  .kokoro/nightly/integration.cfg
  .kokoro/nightly/samples.cfg
  .kokoro/populate-secrets.sh
  .kokoro/presubmit/integration.cfg
  .kokoro/presubmit/samples.cfg
  .kokoro/trampoline.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#97 fix: migrate memcache/v1beta2 to grpc_service_config
  google-cloud-memcache/src/main/java/com/google/cloud/memcache/v1beta2/stub/CloudMemcacheStubSettings.java
  synth.metadata
Labels: automerge, cla: yes, context: full

#102 feat(deps): adopt flatten plugin and google-cloud-shared-dependencies
  .gitignore
  google-cloud-memcache/pom.xml
  grpc-google-cloud-memcache-v1beta2/pom.xml
  pom.xml
  proto-google-cloud-memcache-v1beta2/pom.xml
Labels: cla: yes

#114 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none
