Repository googleapis/java-memcache, pull requests merged in 2021-02, with the labels that each got.

#297 chore: Re-generated to pick up changes from synthtool.
  .github/workflows/ci.yaml
  .kokoro/linkage-monitor.sh
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc11.cfg
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: memcache, cla: yes, context: partial

#298 build(java): update autorelease branch name check
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: memcache, automerge, cla: yes, context: full

#299 chore: Re-generated to pick up changes from synthtool.
  .kokoro/release/publish_javadoc11.cfg
  LICENSE
  synth.metadata
Labels: api: memcache, automerge, cla: yes, context: full

#300 docs: generate sample code in the Java microgenerator
  google-cloud-memcache/src/main/java/com/google/cloud/memcache/v1/CloudMemcacheClient.java
  google-cloud-memcache/src/main/java/com/google/cloud/memcache/v1/package-info.java
  google-cloud-memcache/src/main/java/com/google/cloud/memcache/v1beta2/CloudMemcacheClient.java
  google-cloud-memcache/src/main/java/com/google/cloud/memcache/v1beta2/package-info.java
  synth.metadata
Labels: api: memcache, automerge, cla: yes, context: full, samples

#304 build(java): update autorelease script
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: memcache, automerge, cla: yes, context: full

#305 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: memcache, automerge, cla: yes

#307 ci: linkage monitor CI job to use build.sh
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: memcache, automerge, cla: yes, context: full

#308 chore: update cloud-rad buckets
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  .kokoro/release/publish_javadoc11.cfg
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: memcache, automerge, cla: yes, context: full

#309 build: skip Maven download logs
  .kokoro/build.sh
  synth.metadata
Labels: api: memcache, automerge, cla: yes, context: full

#311 build: reduce download junk in log files
  .kokoro/build.sh
  .kokoro/dependencies.sh
  synth.metadata
Labels: api: memcache, automerge, cla: yes, context: full

#310 chore: update gapic-generator-java to 0.0.20
  google-cloud-memcache/src/main/java/com/google/cloud/memcache/v1/stub/GrpcCloudMemcacheStub.java
  google-cloud-memcache/src/main/java/com/google/cloud/memcache/v1beta2/stub/GrpcCloudMemcacheStub.java
  google-cloud-memcache/src/test/java/com/google/cloud/memcache/v1/CloudMemcacheClientTest.java
  google-cloud-memcache/src/test/java/com/google/cloud/memcache/v1/MockCloudMemcacheImpl.java
  google-cloud-memcache/src/test/java/com/google/cloud/memcache/v1beta2/CloudMemcacheClientTest.java
  google-cloud-memcache/src/test/java/com/google/cloud/memcache/v1beta2/MockCloudMemcacheImpl.java
  synth.metadata
Labels: api: memcache, automerge, cla: yes, context: full

#318 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: memcache, automerge, cla: yes

#319 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: memcache, automerge, cla: yes

#314 feat: promote to 1.0.0
  .repo-metadata.json
Labels: api: memcache, automerge, cla: yes

#321 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: memcache, automerge, cla: yes

#323 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: memcache, automerge, cla: yes

#326 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: memcache, automerge, cla: yes

#328 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: memcache, automerge, cla: yes

#333 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: memcache, automerge, cla: yes
