Repository googleapis/java-memcache, pull requests merged in 2021-05, with the labels that each got.

#386 chore: add enumeration data type to .repo-metadata.json
  .repo-metadata.json
Labels: api: memcache, automerge, cla: yes

#387 build(java): switch to release-please for release tagging
  .github/release-please.yml
  synth.metadata
Labels: api: memcache, automerge, cla: yes, context: none

#390 chore: adding cloud-rad java xrefs
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: memcache, automerge, cla: yes, context: full

#392 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: memcache, automerge, cla: yes

#394 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: memcache, automerge, cla: yes

#395 build(java): remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: memcache, automerge, cla: yes, context: full

#400 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: memcache, automerge, cla: yes

#401 chore: add changelog to cloud-rad
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: memcache, automerge, cla: yes, context: full

#403 feat: add `gcf-owl-bot[bot]` to `ignoreAuthors`
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: memcache, automerge, cla: yes, context: full

#406 chore: dump maven version along with java
  .kokoro/build.sh
  synth.metadata
Labels: api: memcache, automerge, cla: yes, context: full

#409 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: memcache, automerge, cla: yes
