Repository googleapis/java-memcache, pull requests merged in 2021-01, with the labels that each got.

#268 chore: update gapic-generator-java to 0.0.16
  google-cloud-memcache/src/test/java/com/google/cloud/memcache/v1beta2/CloudMemcacheClientTest.java
  synth.metadata
Labels: api: memcache, automerge, cla: yes, context: full

#269 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: memcache, automerge, cla: yes

#271 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: memcache, automerge, cla: yes

#272 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: memcache, automerge, cla: yes

#273 chore: update gapic-generator-java to 0.0.18
  google-cloud-memcache/src/main/java/com/google/cloud/memcache/v1beta2/CloudMemcacheClient.java
  google-cloud-memcache/src/main/java/com/google/cloud/memcache/v1beta2/CloudMemcacheSettings.java
  google-cloud-memcache/src/main/java/com/google/cloud/memcache/v1beta2/stub/CloudMemcacheStub.java
  google-cloud-memcache/src/main/java/com/google/cloud/memcache/v1beta2/stub/GrpcCloudMemcacheCallableFactory.java
  google-cloud-memcache/src/main/java/com/google/cloud/memcache/v1beta2/stub/GrpcCloudMemcacheStub.java
  synth.metadata
Labels: api: memcache, automerge, cla: yes, context: full

#279 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: memcache, automerge, cla: yes

#281 feat: add v1 client
  google-cloud-memcache-bom/pom.xml
  google-cloud-memcache/pom.xml
  google-cloud-memcache/src/main/java/com/google/cloud/memcache/v1/CloudMemcacheClient.java
  google-cloud-memcache/src/main/java/com/google/cloud/memcache/v1/CloudMemcacheSettings.java
  google-cloud-memcache/src/main/java/com/google/cloud/memcache/v1/package-info.java
  google-cloud-memcache/src/main/java/com/google/cloud/memcache/v1/stub/CloudMemcacheStub.java
  google-cloud-memcache/src/main/java/com/google/cloud/memcache/v1/stub/CloudMemcacheStubSettings.java
  google-cloud-memcache/src/main/java/com/google/cloud/memcache/v1/stub/GrpcCloudMemcacheCallableFactory.java
  google-cloud-memcache/src/main/java/com/google/cloud/memcache/v1/stub/GrpcCloudMemcacheStub.java
  google-cloud-memcache/src/test/java/com/google/cloud/memcache/v1/CloudMemcacheClientTest.java
  google-cloud-memcache/src/test/java/com/google/cloud/memcache/v1/MockCloudMemcache.java
  google-cloud-memcache/src/test/java/com/google/cloud/memcache/v1/MockCloudMemcacheImpl.java
  grpc-google-cloud-memcache-v1/pom.xml
  grpc-google-cloud-memcache-v1/src/main/java/com/google/cloud/memcache/v1/CloudMemcacheGrpc.java
  pom.xml
  proto-google-cloud-memcache-v1/pom.xml
  proto-google-cloud-memcache-v1/src/main/java/com/google/cloud/memcache/v1/ApplyParametersRequest.java
  proto-google-cloud-memcache-v1/src/main/java/com/google/cloud/memcache/v1/ApplyParametersRequestOrBuilder.java
  proto-google-cloud-memcache-v1/src/main/java/com/google/cloud/memcache/v1/CloudMemcacheProto.java
  proto-google-cloud-memcache-v1/src/main/java/com/google/cloud/memcache/v1/CreateInstanceRequest.java
  proto-google-cloud-memcache-v1/src/main/java/com/google/cloud/memcache/v1/CreateInstanceRequestOrBuilder.java
  proto-google-cloud-memcache-v1/src/main/java/com/google/cloud/memcache/v1/DeleteInstanceRequest.java
  proto-google-cloud-memcache-v1/src/main/java/com/google/cloud/memcache/v1/DeleteInstanceRequestOrBuilder.java
  proto-google-cloud-memcache-v1/src/main/java/com/google/cloud/memcache/v1/GetInstanceRequest.java
  proto-google-cloud-memcache-v1/src/main/java/com/google/cloud/memcache/v1/GetInstanceRequestOrBuilder.java
  proto-google-cloud-memcache-v1/src/main/java/com/google/cloud/memcache/v1/Instance.java
  proto-google-cloud-memcache-v1/src/main/java/com/google/cloud/memcache/v1/InstanceName.java
  proto-google-cloud-memcache-v1/src/main/java/com/google/cloud/memcache/v1/InstanceOrBuilder.java
  proto-google-cloud-memcache-v1/src/main/java/com/google/cloud/memcache/v1/ListInstancesRequest.java
  proto-google-cloud-memcache-v1/src/main/java/com/google/cloud/memcache/v1/ListInstancesRequestOrBuilder.java
  proto-google-cloud-memcache-v1/src/main/java/com/google/cloud/memcache/v1/ListInstancesResponse.java
  proto-google-cloud-memcache-v1/src/main/java/com/google/cloud/memcache/v1/ListInstancesResponseOrBuilder.java
  proto-google-cloud-memcache-v1/src/main/java/com/google/cloud/memcache/v1/LocationName.java
  proto-google-cloud-memcache-v1/src/main/java/com/google/cloud/memcache/v1/MemcacheParameters.java
  proto-google-cloud-memcache-v1/src/main/java/com/google/cloud/memcache/v1/MemcacheParametersOrBuilder.java
  proto-google-cloud-memcache-v1/src/main/java/com/google/cloud/memcache/v1/MemcacheVersion.java
  proto-google-cloud-memcache-v1/src/main/java/com/google/cloud/memcache/v1/OperationMetadata.java
  proto-google-cloud-memcache-v1/src/main/java/com/google/cloud/memcache/v1/OperationMetadataOrBuilder.java
  proto-google-cloud-memcache-v1/src/main/java/com/google/cloud/memcache/v1/UpdateInstanceRequest.java
  proto-google-cloud-memcache-v1/src/main/java/com/google/cloud/memcache/v1/UpdateInstanceRequestOrBuilder.java
  proto-google-cloud-memcache-v1/src/main/java/com/google/cloud/memcache/v1/UpdateParametersRequest.java
  proto-google-cloud-memcache-v1/src/main/java/com/google/cloud/memcache/v1/UpdateParametersRequestOrBuilder.java
  proto-google-cloud-memcache-v1/src/main/proto/google/cloud/memcache/v1/cloud_memcache.proto
  synth.metadata
  synth.py
  versions.txt
Labels: api: memcache, automerge, cla: yes

#288 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: memcache, automerge, cla: yes

#290 chore: adding docfx doclet resource
  .kokoro/release/publish_javadoc.cfg
  synth.metadata
Labels: api: memcache, cla: yes, context: full

#291 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: memcache, automerge, cla: yes

#293 build: migrate to flakybot
  .kokoro/build.sh
Labels: api: memcache, automerge, cla: yes
